FROM python:3.12-alpine

WORKDIR /app

COPY requirements/backend.txt requirements/backend.txt
RUN pip install --no-cache-dir -r requirements/backend.txt

COPY build/ build/
COPY spaceship/ spaceship/

CMD ["uvicorn", "spaceship.main:app", "--host", "0.0.0.0", "--port", "8080"]